
SETTINGS:
  VIZ: True  # visualize output 
  VIZ_LV: 1  # visualize level 
  NEED_HIST: FALSE # need HISTORY or not
  TRAIN_LIB_PATH: "/home/casxm/albert/uni360/uni360detection/train_library"
  LOCAL_LOG_PATH: "/log"


channel_params:
  "12": 
    img_w: 4000
    img_h: 4096
    axis: 1
    var_threshold: 1.5
    offset: 2
    method: "confidence" # select method to choose best split results, area, width, height, or confidence, default: confidence
    model: 
      label_translator : {0: "end", 1: "mid"}
      iou_thres: 0.45
      conf_thres: 0.6
      imgsz: 640 
      model_path: "./CRH1A-A/weights/channel12_13.pt"
  "13": 
    img_w: 4000
    img_h: 4096
    axis: 1
    var_threshold: 1.5
    offset: 2
    method: "confidence"
    model: 
      label_translator : {0: "end", 1: "mid"}
      iou_thres: 0.45
      conf_thres: 0.6
      imgsz: 640 
      model_path: "./CRH1A-A/weights/channel12_13.pt"
  "14": 
    img_w: 4000
    img_h: 4096
    axis: 1
    var_threshold: 1.5
    offset: 2
    method: "confidence"
    model: 
      label_translator : {0: "end", 1: "mid"}
      iou_thres: 0.45
      conf_thres: 0.6
      imgsz: 640 
      model_path: ""
  "15": 
    img_w: 4000
    img_h: 4096
    axis: 1
    var_threshold: 1.5
    offset: 2
    method: "confidence"
    model: 
      label_translator : {0: "end", 1: "mid"}
      iou_thres: 0.45
      conf_thres: 0.6
      imgsz: 640 
      model_path: ""
  

